//script generated by SiteXpert (www.xtreeme.com)
//Copyright(C) 1998-2003 Xtreeme GmbH
NS60=(navigator.userAgent.indexOf("Netscape6/6.0")!=-1)
Opera=(navigator.userAgent.indexOf('Opera')!=-1)||(navigator.appName.indexOf('Opera')!=-1)||(window.opera)
Opera7=(Opera&&document.createElement!=null&&document.addEventListener!=null)
IE4=(document.all&&!Opera)
mac=((IE4)&&(navigator.appVersion.indexOf("Mac")!=-1))
DOM=document.documentElement&&!IE4&&!Opera
NS4=navigator.appName.indexOf("Netscape")>-1&&!DOM
mswnd=(navigator.appVersion.indexOf("Windows")!=-1||navigator.appVersion.indexOf("WinNT")!=-1)
if(IE4){
av=navigator.appVersion
avi=av.indexOf("MSIE")
if(avi==-1){version=parseInt(av);}else{version=parseInt(av.substr(avi+4));}}
var ver='2.5'
var m1=new Object
m1.name='m1'
m1.fnm='menu_ac_m1'
if(!window.lastm||window.lastm<1)lastm=1
if(NS4||IE4||DOM||Opera){
m1.v17=null
m1.v17Timeout=''
var maxZ=1000
m1.v18
m1.targetFrame
var docLoaded=false
m1.bIncBorder=true
m1.v29=null
m1.v29Str=''
m1.v55=50
m1.scrollStep=10
m1.fadingSteps=8
m1.transTLO=0
m1.fixSB=0
m1.v21="."
m1.maxlev=1
m1.v22=0
m1.bVarWidth=0
m1.bShowDel=0
m1.scrDel=0
m1.v23=150
m1.levelOffset=20
m1.bord=1
m1.vertSpace=5
m1.sep=1
m1.v19=false
m1.bkv=0
m1.rev=0
m1.shs=0
m1.xOff=0
m1.yOff=0
m1.v20=false
m1.cntFrame=""
m1.menuFrame=""
m1.v24=""
m1.mout=true
m1.iconSize=8
m1.closeDelay=1000
m1.tlmOrigBg=""
m1.tlmOrigCol="White"
m1.v25=false
m1.v52=false
m1.popupOpacity=75
m1.v11=false
m1.v10=0
m1.popupLeftPad=5
m1.v54=0
m1.v01=2
m1.tlmHlBg="#7D7F8E"
m1.tlmHlCol="White"
m1.borderCol="white"
m1.menuHorizontal=true
m1.scrollHeight=6}
m1.lev0=new Array("11px",false,false,"Black","#BEC0D5","White","Arial,Helvetica","#7D7F8E")
m1.lev1=new Array("11px",false,false,"Black","#BEC0D5","White","Arial,Helvetica","#7D7F8E")
m1.lev2=new Array("11px",false,false,"Black","#BEC0D5","White","Arial,Helvetica","#7D7F8E")
m1mn1=new Array
(
"AST-Probatch","microsite/index.php",0,"",""
,"AST-Activities Manager","AST_Activity_Manager.php",0,"",""
,"COE","COE.php",0,"",""
,"COBIS","COBIS.php",0,"",""
,"Acsel-e","Acsel_e.php",0,"",""
,"Acsel-x","Acsel_x.php",0,"",""
,"Iflex Pro","iFlex_Pro.php",0,"",""
)
m1mn2=new Array
(
"Banca","",1,"",""
,"Seguros y reaseguros","",1,"",""
)
m1mn2_1=new Array
(
"AST-Probatch","microsite/index.php",0,"",""
,"AST-Activities Manager","AST_Activity_Manager.php",0,"",""
,"COE","COE.php",0,"",""
,"COBIS","COBIS.php",0,"",""
)
m1mn2_2=new Array
(
"Acsel-e","Acsel_e.php",0,"",""
,"Acsel-x","Acsel_x.php",0,"",""
,"Iflex Pro","iFlex_Pro.php",0,"",""
)
absPath=""
if(m1.v19&&!m1.v20){
if(window.location.href.lastIndexOf("\\")>window.location.href.lastIndexOf("/")) {sepCh = "\\" ;} else {sepCh = "/" ;}
absPath=window.location.href.substring(0,window.location.href.lastIndexOf(sepCh)+1)}
m1.popupOffset=0
m1.v02=m1.v23
if(Opera&&!Opera7)document.write("<"+"script language='JavaScript1.2' src='./menu_opera.js'><"+"/"+"script>")
else if(NS4)document.write("<"+"script language='JavaScript1.2' src='./menu_ns4.js'><"+"/"+"script>")
else if(document.getElementById)document.write("<"+"script language='JavaScript1.2' src='./menu_dom.js'><"+"/"+"script>")
else document.write("<"+"script language='JavaScript1.2' src='./menu_ie4.js'><"+"/"+"script>")
document.write("<style type='text/css'>\n")
document.write(".m1CL0,.m1CL0:link{text-decoration:none;width:100%;color:White; }\n")
document.write(".m1CL0:visited{color:White}\n")
document.write(".topFold{position:"+(!DOM&&!IE4?"relative":"static")+"}\n")
if(NS4&&!m1.v25)document.write(".x1{padding-left:15px;padding-right:15px;}\n")
document.write(".m1mit{"+((!NS4||m1.v25)?"padding-left:15px;padding-right:15px;":"")+"color:White; font-weight:bold; font-family:Arial,Helvetica; font-size:11px; }\n")
document.write("</style>\n\n")
